### ISSUE TITLE
Faulty link

### ISSUE THREAD

**Issue by rjlatail** [learn-co-curriculum/dsc-stat-learning-theory-v2-5#1]
## Link to Canvas

https://learning.flatironschool.com/courses/7248/pages/statistical-learning-theory?module_item_id=658162

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x ] Other (explain below)

### Source

```
The final link on the page does not go to the correct location (the one with the text "An Overview of Statistical Learning Theory with examples").  The URL includes a tilde, but clicking on the link tries to load a URL that replaces the tilde by '%7E', which seems like an encoding issue. 
```

### Concern

If the user is attentive and interested, he can figure out what's going on, but at first it just seems like a broken link

## (Optional) Proposed Solution

Inspect the link to determine whether there was an error when the link was created.

## What OS Are You Using?

- [ ] OS X
- [ x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you. We'll take a look.

**Comment by bpurdy-ds** [comment]
Thank you for flagging this. The link is now updated. Let us know if there is anything else.
